### ISSUE TITLE
Custom layout URL should have storage link.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#108]
http://www.screencast.com/t/Mov6SPUUvbR

In addition to the URL portion of the custom layout selector, there should be a link to access the layout in Rise storage.

**Comment by stulees** [comment]
@btfrise @alanclayton This is now complete. URL Field component now has Storage Selector component integrated, changes have been made in Spreadsheet Widget and the Widget has been re-built to include the latest URL Field. Please test and verify (test version). Thanks

**Comment by btfrise** [comment]
Verified. Closing.
