### ISSUE TITLE
Custom layouts hosted in Rise storage do not work.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#109]
Tested using 
https://github.com/Rise-Vision/widget-google-spreadsheet/blob/feature/custom-layouts/examples/list.md
https://docs.google.com/spreadsheet/ccc?key=0Av0wEY9sizgUdDVjN09uQTYwZHd3ZkU0dGh4TURLSHc#gid=0

1) Upload custom layout to Rise Storage.
2) Generate link to custom layout in storage.
3) Add link to custom layout URL field in placeholder.
4) Save presentation and preview.

The custom layout will not load from Rise Storage. A blank presentation loads with the following error in console. http://www.screencast.com/t/hT0oL5wkYUMT

**Comment by stulees** [comment]
@btfrise @alanclayton This is fixed. URL Field component now has Storage Selector component integrated, changes have been made in Spreadsheet Widget and the Widget has been re-built to include the latest URL Field. Please test and verify (test version). Thanks

**Comment by btfrise** [comment]
Verified. Closing.
