### ISSUE TITLE
Include Entire Sheet/Range of Cells not working as intended.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#112]
1) Set widget to include entire sheet
2) Preview to see entire sheet displayed
3) Set widget to include range of cells example a1:b10
4) Preview to see selected cells displayed
5) Set widget to include entire sheet
6) Preview to see a1:b10 are the only cells displayed
7) Set widget to include range of cells, then set to include entire sheet
8) Preview to see entire sheet displayed.

http://www.screencast.com/t/3pk0HLRT

The spreadsheet widget is not immediately recognizing when a user switches from range of cells to entire sheet.

It should function as:
1) Set widget to include entire sheet
2) Preview to see entire sheet displayed
3) Set widget to include range of cells example a1:b10
4) Preview to see selected cells displayed
5) Set widget to include entire sheet
6) Preview to see entire sheet displayed

**Comment by alanclayton** [comment]
@btfrise I'm unable to replicate this. I'm going to close this. Let me know if you see it again.
