### ISSUE TITLE
Spreadsheet content does not fit placeholder when there is only one column in the spreadsheet and the font size is greater than 30.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#114]
Steps to reproduce:
1. Add spreadsheet with only one column to spreadsheet widget.
2. Set data font to 30+

Result:
Spreadsheet widget cuts off content in the placeholder.

How it should work:
The spreadsheet widget should be fully responsive and fit all content into the placeholder regardless of size or amount of content.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=fcbae24f-ec23-4622-9981-7a50c771726c

OS:
ChromeOS/Windows/Linux

Chrome Ver:
 41.0.2272.89

**Comment by stulees** [comment]
@btfrise Just to clarify, this issue appears to be dependent on font size. I think the title of this bug needs to mention that, thanks.

**Comment by Dickfoto** [comment]
I am the end user.  Any progress on this?

**Comment by stulees** [comment]
@Dickfoto This is in my queue of items to address but I have other projects outstanding at the moment that need to be completed first. I'll be sure to notify you here on this issue when progress has been made, thanks.

**Comment by alanclayton** [comment]
Issue appears to be related to text that is bold. To replicate, add enough text in a cell so that it will wrap in the presentation.

**Comment by alanclayton** [comment]
Can't replicate in new widget.
