### ISSUE TITLE
Last row in spreadsheet replaced by first row after ~5 minutes using custom layouts

### ISSUE THREAD

**Issue by ptseng** [Rise-Vision/widget-google-spreadsheet#116]
Presentation: http://preview.risevision.com/Viewer.html?type=presentation&id=cfb8390b-e947-4f5b-9b40-49851b253850

Reproduction Steps

1. Load up presentation
2. Presentation is based on custom layout
3. Wait about 5 minutes

What you expected to happen.

1. Presentation should stay the same after five minutes.

Actual Results

1. Last row of presentation gets replaced by first row of presentation after about five minutes.

If you need to look at the custom layout, please let me know and I can send you a link privately. 

Thanks!

**Comment by ptseng** [comment]
After about an hour the last row disappears completely.  It also looks like the width of the beer column got smaller.

**Comment by ptseng** [comment]
Any update on this?  Kind of a huge bug right?

**Comment by stulees** [comment]
@ptseng If you can determine that this is also a bug with the default layout of this Widget, then the bug can get queued to address. Please provide a presentation that illustrates the bug with the default layout. 

However, if what you're experiencing only happens with your custom layout, then my advice is to try and replicate the issue with the example custom layout provided in this repo here - https://github.com/Rise-Vision/widget-google-spreadsheet/blob/master/examples/images.md . If you can do so, please provide your presentation that illustrates the bug using the example custom layout.

Thanks

**Comment by ptseng** [comment]
@stulees I will try with the example custom layout.  However, in the example custom layout: 

```
      <td class="A"></td>
      <td class="B image"></td>
      <td class="C qrCode"></td>
```

Provides for 3 columns.  All of the columns are of a different type.  A is text, B is an image and C is a qrCode.  It may not be sufficient to demonstrate this bug where the last row is being replaced by the first row upon update.  Would you accept a demonstration where:

```
      <td class="A"></td>
      <td class="B"></td>
      <td class="C"></td>
```

??

**Comment by ptseng** [comment]
@stulees with reference to the above, using the custom layout provided in images.md, I have replicated this bug.  

Presentation: http://preview.risevision.com/Viewer.html?type=presentation&id=41b27724-ee4d-4628-8b33-359e8a99026b

As mentioned before, takes about 5-10 minutes.  The last row will be replaced by the first row.

Please take a look into this.  Thanks for your consideration.

**Comment by stulees** [comment]
@ptseng Thanks for providing this. I have other projects and priorities at the moment, but this is being queued up to work on in the near future. I will inform you of any progress. In the meantime, if you can, provide as much insight and detail regarding the bug and/or where you think it might be occurring in the source code. Thanks

**Comment by ptseng** [comment]
@stulees Thank you.  It seems that the bug is happening on update, so I would check the update code for an "index off by one" error when iterating through rows.  That is my primary suspicion.

**Comment by ptseng** [comment]
@stulees Can we get an update on this?  I have been using the 'Gadget' for now.  I would be fine with continuing to use the 'Gadget' but I can no longer access the settings of the gadget.  Community.risevision has said that the 'Gadget' is now replaced with the 'Widget'.  However, I can't use the 'Widget' until this bug is fixed.  Please help.

**Comment by alanclayton** [comment]
Hey @ptseng we've recently finished building a Web Component (http://webcomponents.org/) that retrieves data from a Google Spreadsheet. Our intention is to replace our current Spreadsheet Widget with a new version that uses this Web Component. What other types of data are you showing in your Presentation that contains the Spreadsheet Widget? Could this be an option for you to migrate to? 

Here is a simple (rough) HTML page that uses the Spreadsheet Component, https://storage.googleapis.com/risemedialibrary-3c86db8b-5ab5-4ee1-85a5-284317371990/spreadsheet-component/index.html. 

If you are interested, take a look at the ReadMe here, https://github.com/Rise-Vision/web-component-rise-google-sheet and let me know if there is anything we can do to help. Thanks!

**Comment by ptseng** [comment]
@alanclayton This looks interesting.  I'll take a look at it when some time opens up.  For now, I will continue to use the Gadget.  I was able to access the settings with some help from community.risevision.

**Comment by stulees** [comment]
@ptseng FYI, we just deployed an update to the Widget that corrects this issue now.

**Comment by ptseng** [comment]
@stulees Thanks for fixing!
