### ISSUE TITLE
Mixed format columns result in data not appearing or data not appearing correctly. 

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-google-spreadsheet#117]
There are two scenarios where this issue occurs.

Scenario 1:
I have a column of with data that is formatted as "Plain Text" and "Number". In this scenario, the "Plain Text" data does not appear in the Spreadsheet.

In the Widget Settings, specify a column header of 1 and enable the column formatting option. 

Scenario 2:
I have a column of data that is formatted as "Plain Text" and have enabled column formatting. The data from one of the cells is 1.23. What actually shows in the presentation is "1". It should show the actual value of 1.23. 

The Presentation linked below contains two placeholders, "one" and "two". Placeholder "one" replicates what is described in Scenario 1 above. Placeholder "two" replicates Scenario 2 above.

Presentation: http://goo.gl/OIT8ka

Spreadsheet: https://goo.gl/GIjLF6

**Comment by AlexKolenoff** [comment]
@alanclayton Can you set a priority on this?

**Comment by btfrise** [comment]
@alanclayton We've gotten a few more reports of leading 0s causing this issue in the Spreadsheet Widget. Is this something we can get in your backlog?

**Comment by btfrise** [comment]
@alanclayton we have an open issue for this on the community. https://getsatisfaction.com/rise_vision_inc/topics/can-i-display-leading-0s-in-google-spreadsheet

**Comment by stulees** [comment]
@btfrise @alanclayton Closing as scenario 2 has been fixed by PR #125 and scenario 1 is a limitation of the Visualization API when mixed formats are used.
