### ISSUE TITLE
After updating spreadsheet, widget goes blank and subsequent updates do not show up

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-google-spreadsheet#118]
Steps to reproduce:
1. Start with a working presentation that correctly displays content from a google spreadsheet
2. Modify the spreadsheet (there wasn't a specific trigger that ALWAYS caused the issue, but adding an additional column (exceeding 3) frequently did)

Result:
Widget will update, showing a blank screen (no content from the spreadsheet).
* Modifying the spreadsheet after the screen goes blank does not result in any change.
* If the presentation is republished or schedule is changed, the updated content will appear.

How it should work:
Widget updates, showing new content.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=73176d84-da83-427a-8f72-55e00f6e3162?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Ubuntu 14.04, Win7, Win8, OSX, ChromeOS

Chrome Ver:
Stable, Beta & Dev

**Comment by btfrise** [comment]
@stulees @alanclayton This is now fixed. I'll go ahead and close it up.
