### ISSUE TITLE
DataTables error message when auto scroll is used with custom layout.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#128]
Steps to reproduce:
1. Add a custom layout to a Google Spreadsheet Widget
2. Set auto scroll to "By page" or "Continuously"

Result:
After 5 to 10 minutes, a DataTables error appears 
"DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter '5' for row 0. For more information about this error, please see http://datatables.net/tn/4"
http://www.screencast.com/t/QD1jJPkSEsY

How it should work:
Spreadsheet Widget should scroll as normal with Custom Layout.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=ff475e76-51c5-4280-8db0-e656b6bcc397

OS:
Windows 8.1 / Ubuntu 14.04 / OS X

Chrome Ver:
44.* & 45.*

Log as bug, assign to developer responsible for repo.

**Comment by btfrise** [comment]
@alanclayton FYI.

**Comment by Hobadee** [comment]
Having this same issue.

I believe the issue is related to columns without data in them and DataTables attempting to access null data.

**Comment by rodrigopavezi** [comment]
Custom layouts is going to be replaced by the use of the sheets component https://github.com/Rise-Vision/rise-google-sheet.
