### ISSUE TITLE
Content duplicated upon data refresh when a non-table custom layout used

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/widget-google-spreadsheet#130]
Steps to reproduce:
1. Add a custom layout to a Google Spreadsheet Widget that does not use a `<table>`

Result:
After 5 minutes (data refresh), content is duplicated - http://screencast.com/t/opKka6yKLD

How it should work:
Content should not be duplicated

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=d678539b-9c3e-4f89-a488-0c27149381ba

OS:
Windows 8.1 / Ubuntu 14.04 / OS X

Chrome Ver:
44.* & 45.*

Log as bug, assign to developer responsible for repo.

**Comment by alanclayton** [comment]
@stulees do you recall where this conversation was left?

**Comment by stulees** [comment]
@alanclayton I know this is still an open bug, no fix has been worked on or deployed.

**Comment by reynolds5520** [comment]
@stulees 
This presentation may help troubleshoot.  It shows how the error repeats without a lot of extra data in the way.  [http://preview.risevision.com/?type=presentation&id=55ba54a4-8a9d-45b9-8198-23dfb4eea026](url)

When the page first loads the data is properly displayed for rows 1, 2, 3, 4, 5, 6.

When refreshed after 5 minutes it changes to 1, 2, 3, 4, 5, 1, 1, 2, 3, 4, 5, 2, 1, 2, 3, 4, 5, 3, 1, 2, 3, 4, 5, 4, 1, 2, 3, 4, 5, 5, 1, 2, 3, 4, 5, 6

**Comment by btfrise** [comment]
@alanclayton The user here https://community.risevision.com/rise_vision_inc/topics/google-sheets-gadget-down?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_16752342 is being impacted by this defect.

**Comment by rodrigopavezi** [comment]
Custom layouts is going to be replaced by the use of the sheets component https://github.com/Rise-Vision/rise-google-sheet.
