### ISSUE TITLE
Content not updating from Spreadsheet

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#131]
Reproduction Steps

1. Added Google Spreadsheet Widget to Presentation with refresh rate set to 5 minutes
2. Displayed presentation on live display
3. Updated cell in spreadsheet

ONLY OCCURS ON CHROME APP PLAYER

The widget on the display did not update. 

During an inspection of the console, it looks like the widget is receiving the updated information from the spreadsheet, it is just not appearing.

![image](https://cloud.githubusercontent.com/assets/8458926/10672463/0aa86e14-78b6-11e5-93fc-1edb56d9588b.png)

I have recreated a simplified presentation here
http://preview.risevision.com/Viewer.html?type=presentation&id=1d454d1b-32de-47ef-9d48-2425e2c547d4
With an editable copy of the spreadsheet here
https://docs.google.com/spreadsheets/d/1fmIuG7TC7boTR4PcidmLiGKAeeydRzPNaDL9KcCy9_k/edit#gid=1810222646

**Comment by alanclayton** [comment]
Issue was fixed with #132
