### ISSUE TITLE
Transparent background option disappears in Placeholder

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-google-spreadsheet#133]
**How to recreate**
Add a Google Spreadsheet Placeholder in the new Editor. Configure the background color from transparent to something else then try to configure it back to transparent.

**How it is working now**
The transparent option is not available. See http://recordit.co/BaCgY6cyTC

**How it should work**
The transparent option should be available after choosing color.

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1771813391

**Comment by alanclayton** [comment]
@lapinnoir I assume we can just inform Users to manually enter rgba(0,0,0,0) until we start the Spreadsheet Widget Epic?
