### ISSUE TITLE
Widget doesn't compile on latest toolkit versions

### ISSUE THREAD

**Issue by Hobadee** [Rise-Vision/widget-google-spreadsheet#136]
I tried to compile this widget using the latest versions on Node.js, Bower, and Gulp.  It failed hardcore.

First failure was in `npm install`; It appears several libraries being used are deprecated.  (Getting Warnings for them.)  As well, phantomjs is failing to install.

Not familiar with Bower, but I'm getting error-y looking lines.  ("invalid-meta" and "mismatch")  I also get a error: "Unable to find a suitable version for angular-bootstrap"

Gulp fails as well.

**Comment by stulees** [comment]
@Hobadee Thanks for raising this. We will be doing substantial refactoring to this Widget in the next coming weeks which will resolve whatever build issues you are currently experiencing and will resolve other outstanding issues also. Cheers
