### ISSUE TITLE
Per Column Formatted column widths do not adhere to what you enter

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#216]
<b>How it works now:</b>
1. In a placeholder that is 1200 pixels wide, showing a spreadsheet that has 5 columns, set the Width of one column to 500, and the others to 20.
2. Notice that the one column does not go to 500 pixels, it remains at 100, while all the others go to 20.

For further clarification: https://goo.gl/t9sdVl

Presentation: http://goo.gl/kmtd2L

<b>How it should work:</b>
As long as you have the space for it, the entered pixel size for every pre formatted column should be adhered to.

**Comment by donnapep** [comment]
@robb-price I need access to the spreadsheet. Can you share it with me? Thx.

**Comment by robb-price** [comment]
Confirmed and closed.
