### ISSUE TITLE
Per Column Formatting not applying when using a custom range

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#219]
<b>How it works now:</b>
1. In the early preview Spreadsheet Widget, select a custom range.
2. Set Per Column formatting for any column in the spreadsheet.
3. Preview or play the Presentation on a Display, and notice that the Per Column formatting options are not adhered to. If you remove the custom range and show the entire sheet, the per column formatting works.

<b>How it should work:</b>
Regardless if you are using a custom range or the entire spreadsheet, the per column formatting should be adhered to.

**Comment by donnapep** [comment]
@robb-price Had some trouble reproducing, but apparently it's only an issue when the header is not included as part of the range data.

**Comment by robb-price** [comment]
@donnapep Have you put that notification in as discussed on the Trello Card? Can we close this?

**Comment by donnapep** [comment]
@robb-price It's currently in progress but should go out today.
