### ISSUE TITLE
Per Column Formatting does not work for certain spreadsheets

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#221]
<b>How it works now:</b>
Look at <a href="https://apps.risevision.com/editor/workspace/13008cb2-aca8-4b57-b4be-c484f1c59951/true?cid=556323b8-984c-4127-aa08-4d73d019bcb8">Presentation A</a>, using <a href="https://docs.google.com/spreadsheets/d/1jOTmCVnlC5CeGCuojN5BWsswpdEv2CYb0g5foxlW1LA/edit#gid=0">Spreadsheet A</a>. Notice that Per Column Formatting works. The name of the column I selected in Per Column Formatting is the data in the first cell in the column.

Look at <a href="https://apps.risevision.com/editor/workspace/2745a563-e0b5-4012-9fbf-830639a6e68b/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">Presentation B</a>, using <a href="https://docs.google.com/spreadsheets/d/1aAlSzaD8Y1CFjHO2w7RQ5MpUH81lciyXRKQAJCpcKuU/edit#gid=0">Spreadsheet B</a>. Notice that Per Column Formatting does NOT work. The name of the column I selected in Per Column Formatting is the column name, NOT the data in the first cell of the column.

<b>How it should work:</b>
Regardless of the spreadsheet, Per Column Formatting should adhere to the settings you have selected in the Widget.

**Comment by alanclayton** [comment]
@robb-price This is fixed and deployed.
