### ISSUE TITLE
Custom Width stops working when you enter a second column in Per Column Formatting.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#225]
<b>How it works now</b>
1. Have 1 column set in per column formatting, and confirm it looks as expected.
2. Enter another column into the Widget settings, and notice you can now no longer see either column that was there previously.

For further clarification: https://goo.gl/rHcaSo

Presentation to test with: https://apps.risevision.com/editor/workspace/b571db24-723f-4a9e-b0d5-9a5d293ee365/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

@stulees This is the bug we were discussing earlier that you wanted me to log to remind you to test it :)

**Comment by alanclayton** [comment]
@robb-price this is fixed.
