### ISSUE TITLE
Spreadsheet Widget is not showing second column of Spreadsheet

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#229]
Further details on the issue

The Widget is assuming that since the first row of a column is empty, there is no additional data to show.  

To replicate, 
Configure the Widget to show Sheet 1 range A1:D10 from https://goo.gl/SjkMXS. 

Clear all values from Row 1. When you Preview the Presentation no data appears. 

If you add a space to C1 but leave A1 and B1 empty. The values from A1:C10 will now appear, but not Column D values.

Remove the Space from C1 and add a space to D1. Preview and all the data will appear. 

The Widget should show all the data as it has been configured regardless of the values in Row 1. 

_____

Original description of the problem. 

<b>How it works now:</b>
1. Using <a href="https://apps.risevision.com/editor/workspace/62665461-1e1b-42cf-8b7e-8b7477ac522b/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, notice that there are 2 instances of the Spreadsheet Widget, one is set to have a range, the other is set to show the entire sheet. 
2. Preview or play the Presentation on a Display, and notice that Column B never shows in the Presentation in either Placeholder.

For further clarification: https://goo.gl/1edWJz

The Spreadsheet has edit rights for anyone with the link.

**Comment by ByronDarlison** [comment]
@robb-price @alanclayton is this issue still open?

**Comment by alanclayton** [comment]
@ByronDarlison This is still open and queued up to be fixed next week.

**Comment by alanclayton** [comment]
Fixed with #231
