### ISSUE TITLE
Data is not displayed if the first row of the spreadsheet is blank

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-google-spreadsheet#230]
How it works now:
If the first row of the spreadsheet is blank, the component will not show any data on the presentation. Inspecting the element will show that the rows have been created, but do not contain any text data.

How it should work:
The data would be displayed with a gap at the top representing the blank cell, in the same way that empty rows between cells with data create gaps.

Example:
This presentation has been set up with a spreadsheet with the first row blank: https://apps.risevision.com/editor/workspace/25191520-a815-496e-b8f9-0aade0af58ca/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

The spreadsheet can be accessed here:https://docs.google.com/spreadsheets/d/1r-FO2JnnVic4_XHDqI-Jwb_dmZvjm9CgMEbx79x6tV4/edit#gid=0

**Comment by ByronDarlison** [comment]
@pcsandford curious, what happens if there is a blank row in the middle?

**Comment by pcsandford** [comment]
@ByronDarlison if there is a blank row in the middle it will create a gap equal to the size of the row setting. Thanks!

**Comment by alanclayton** [comment]
@ByronDarlison @pcsandford I'm going to close this as it is a duplicate to https://github.com/Rise-Vision/widget-google-spreadsheet/issues/229 which we will have fixed next week. In the interim, a simple work around is to add a space to the cells in the top row. I added the space to your sample Spreadsheet https://goo.gl/SjkMXS and you can now see the data showing in the Presentation.

**Comment by ByronDarlison** [comment]
@alanclayton I don't follow how this is a duplicate to the other issue? And the work around is easy, it is the noise that it causes that isn't...

**Comment by alanclayton** [comment]
@ByronDarlison Sorry about that. I've updated the description on #229 to better explain what is going on.  And understood on the noise.
