### ISSUE TITLE
Last row is not displayed when scrolling if 1st row is set as header

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-google-spreadsheet#232]
**How it works now:**

Example presentation: https://apps.risevision.com/editor/workspace/d1d45d6e-20d6-40eb-a1ff-0229cc830ec8/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

Example spreadsheet: https://docs.google.com/spreadsheets/d/1yr1B6PzBEwtmvVm3eiov7LyniGqJLzTrFuvqkqR-1Xg/edit#gid=0

In this presentation the spreadsheet on the right has the first row set as the header and will only scroll to show TEST ROW 14 as the last row, cutting off TEST ROW 15 before the scroll is reset to the start. The spreadsheet on the left has no header set and correctly shows TEST ROW 15 before the scroll is reset.

I have tested the spreadsheet widget on the right both with setting a range and displaying the full sheet and get the same results.

Thanks!

**Comment by stulees** [comment]
@pcsandford This has been fixed by PR #233 , closing, thanks!
