### ISSUE TITLE
Horizontal Scroll Bar Showing Up

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-google-spreadsheet#234]
Horizontal Scroll Bar shows up if the placeholder is not vertically tall enough.
http://www.screencast.com/t/IyFudDcwf

When a user sees this scroll bar it leads them to think there is not enough horizontal space given it is also cutting off the right side of the data. However changing column widths or the width of the placeholder does not get rid of it.
It took me a while to figure out it was the height of the placeholder that needed to be adjusted before it would go away.

I don't think we should be showing any scrollbars.

Here is an example:
https://rva.risevision.com/#/PRESENTATION_MANAGE/id=18fcffe0-49a9-4bae-bfc7-8c14b266af1b?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Comment by rodrigopavezi** [comment]
@mmeiers could you please verify if the issue has been fixed with this version of the widget?

http://s3.amazonaws.com/widget-google-spreadsheet-test/stage-0/2.0.0/dist/widget.html

Cheers

**Comment by mmeiers** [comment]
@rodrigopavezi 👍 looks to be fixed thanks

**Comment by rodrigopavezi** [comment]
Fix has been deployed https://github.com/Rise-Vision/widget-google-spreadsheet/pull/236 cheers
