### ISSUE TITLE
When using a specific spreadsheet with a range, you can't select certain columns to format

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#243]
<b>How it works now:</b>

Using <a href="https://apps.risevision.com/editor/workspace/72640bae-a27d-4da9-9972-d6b09f097325/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, notice how you cannot select the column J to format, even though it is included in the Spreadsheet range. You can select I and K, but not J. This does not happen with other Spreadsheets.

For further clarification: https://goo.gl/b8RYc6

<b>How it should work:</b>
Regardless of the spreadsheet, you should have all columns available to format if they are included in the range.

**Comment by alanclayton** [comment]
Issue is due to use of old version.
