### ISSUE TITLE
Border Between Columns Showing up

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-google-spreadsheet#251]
When "Show Separator Between Columns" is unchecked there is still a border that shows between columns. Turning on the separator and making it transparent does not fix the issue.
http://www.screencast.com/t/MqXtAea42wUL

The desired outcome is to have no gap between columns so the alternate row is one seamless background.

I believe the following css property should solve the issue: border-collapse: collapse; 

example presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=8e04c4d6-4ea2-4b47-ae1d-77ad771a941e?cid=d0b5f2b2-3547-4805-93ee-8b11aea3d658

**Comment by rodrigopavezi** [comment]
This has been fixed by https://github.com/Rise-Vision/widget-google-spreadsheet/pull/252. cheers
