### ISSUE TITLE
If you have content with different lengths, the row height doesn't auto adjust for longer text

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#253]
<b>How it works now:</b>
1. Using a Spreadsheet that has a lot of different lengths of text to show in your spreadsheet. 
2. Put that into a Widget, and notice that the longer text gets cut off instead of showing completely. The only way to get it to show all content, is to increase the Row Height, which increases it for ALL rows, which users may not want.

Presentation and Spreadsheet to test with: https://apps.risevision.com/editor/workspace/4d810c2a-d179-4c79-80a4-9904c8236d36/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

We have a <a href="https://github.com/schrodinger/fixed-data-table-2/issues/25">bug</a> open with React about this, but we really need a workaround that users can use.

**Comment by robb-price** [comment]
@stulees Any news of a workaround on this?

**Comment by stulees** [comment]
@robb-price I asked for latest status on the [bug](https://github.com/schrodinger/fixed-data-table-2/issues/25), waiting for a response. Otherwise we are discussing on Trello card - https://goo.gl/0chgZy

**Comment by sheadarlison** [comment]
@alanclayton Was there a conclusion on this?

**Comment by alanclayton** [comment]
@sheadarlison no, was dependent on this defect being fixed, https://github.com/schrodinger/fixed-data-table-2/issues/25.

**Comment by sheadarlison** [comment]
This is a feature request not a defect, the widget is behaving as it's supposed to. Closing the defect.
