### ISSUE TITLE
Row padding prevents row data from being aligned vertically

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-spreadsheet#254]
If data is configured to be aligned top or bottom, there is padding which prevents the data from being fully aligned top or bottom. See here for an example. http://www.screencast.com/t/XpFb6DIVm6

To replicate, 

1. Configure the Widget to show the range A2:B3. 
2. Set Row height to be 60px
3. Set font size for both header and body to 30px
4. Set vertical alignment for top.

**Comment by alanclayton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Spreadsheet Widget Issue 134](https://trello.com/c/RG7iWTUF/2429-spreadsheet-widget-issue-134)

**Comment by stulees** [comment]
@alanclayton Do you have the link to the presentation and/or spreadsheet that is being used in your screenshot?
