### ISSUE TITLE
Row colour picker blocks manual input, and RGBA values no longer work

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/widget-google-spreadsheet#258]
### Issue:
When selecting the odd or even row colour, the popup blocks the manual input field so you can't see the actual RGBA colour values. This happens at different screen sizes. When the A value of RGBA is entered at a value less than 1 the opacity is not shown in the presentation.

### Steps to Replicate:

1. Set up a placeholder with the Google Spreadsheet widget;
2. Click on the odd or even row colour input and see the popup blocks the input:
<img width="561" alt="screen shot 2017-01-25 at 1 09 50 pm" src="https://cloud.githubusercontent.com/assets/8008948/22303287/9cac4f50-e300-11e6-928f-9796195ae5f8.png">
3. Change the A value using the vertical dragging input and preview the presentation - the background will show as solid black (or whatever colour was selected)

### What should happen

1. The popup should be above or to the side of the numerical RGBA input.
2. The alpha value of RGBA should be shown in the presentation

Example presentation here for testing: https://apps.risevision.com/editor/workspace/f67b5506-90df-4f9d-9f9a-9b842477b70f/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Comment by stulees** [comment]
@pcsandford I'm not able to recreate the issue regarding alpha value not being applied. I can enter any value between 0 and 1 (eg. 0.5) and it is applied. Here's a presentation for demo - https://apps.risevision.com/editor/workspace/36c2e57a-4198-4b08-8b28-bc9d95b1cb12/?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013 

Can you clarify how you weren't able to see it applied or confirm it's not an issue, cheers.

**Comment by pcsandford** [comment]
@stulees I have changed the value in the presentation and attached a screenshot of what I was seeing. I should have been clearer as I was initially using an opacity on black so it was more obvious but in the attached screenshot you can see that the areas around the text are darker than the desired opacity - I think in my presentation my row height was almost equal the text height so it gave the impression of it not being applied at all. Thanks!
<img width="375" alt="screen shot 2017-02-08 at 3 50 35 pm" src="https://cloud.githubusercontent.com/assets/8008948/22756881/b3b84c8c-ee16-11e6-875f-8868019eba78.png">

**Comment by alanclayton** [comment]
Fix deployed
