### ISSUE TITLE
Horizontal Scroll bars

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-google-spreadsheet#261]
**What is not working/What is currently happening:**
When the content is to wide for the placeholder a horizontal scrollbar appears and there is no way to hide or remove it. 

**What is expected to work/What is the client expecting:**
You are able to show or hide the horizontal scrollbar. 

**What has been tried so far:**
Nothing. 

**Links**
http://preview.risevision.com/?type=presentation&id=11178ab5-e102-46f8-a56f-22969ca52778&showui=false

https://apps.risevision.com/editor/workspace/11178ab5-e102-46f8-a56f-22969ca52778/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

![screen shot 2017-01-31 at 11 36 18 am](https://cloud.githubusercontent.com/assets/9273546/22481326/d6d49c66-e7c2-11e6-963f-a4cce08bb323.png)

**Comment by alanclayton** [comment]
Fix deployed.
