### ISSUE TITLE
Title Case Not Consistent in Settings

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#268]
![spreadsheetwidgettextformatting](https://cloud.githubusercontent.com/assets/8458926/24764536/4690ac8c-1aba-11e7-9fe5-4fcc42ea4278.jpg)

In Google Spreadsheet Settings, API Key(1) is Title Case and API key(2) is not. This should be consistent.

**Comment by stulees** [comment]
@btfrise This has been fixed, thanks.
