### ISSUE TITLE
Redirect "How to create API key ..." link to Knowledge Base.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#270]
Google Spreadsheet Widget currently links to https://community.risevision.com/rise_vision_inc/topics/how-to-generate-an-api-key-for-the-google-spreadsheet-widget

This has been added to the Knowledgebase, the link should now direct to https://risevision.zendesk.com/hc/en-us/articles/115002245846

@alanclayton FYI

**Comment by alanclayton** [comment]
Update deployed.
