### ISSUE TITLE
Selecting a Size for font is not working correctly in Presentations

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#271]
<b>How it works now:</b>
1. Add the Spreadsheet Widget to your Company.
2. Set the font size to be larger than the default, notice that the size in the Widget does not update in the dropdown, however the size of the font updates in the text example.
3. Notice that the size of the font is not updated in your Presentation preview or on the Display.

For further clarification; https://goo.gl/OFnikf

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 271 - Selecting a Size for font is not working correctly in Presentations](https://trello.com/c/zeuKlWNT/4179-issue-271-selecting-a-size-for-font-is-not-working-correctly-in-presentations)

**Comment by stulees** [comment]
@robb-price Fixed with PR #272 , thanks.
