### ISSUE TITLE
Error when accessing spreadsheet

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-google-spreadsheet#277]
**Problem**
When this Presentation plays on this Display after a couple hours the placeholder with the Spreadsheet Widget shows the error: "Error when accessing spreadsheet" and it doesn't seem to disappear. 

- Presentation: https://apps.risevision.com/editor/workspace/bb6f7763-f5d2-4566-919e-346ea5eb3fb4/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f
- Display: https://apps.risevision.com/displays/details/HXXHCTR5AQFQ?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f
- SC: https://connect.risevision.com/Host#Access/*Rise%20Display%20Creative//146fac0f-471a-411f-858e-ed881d8c8b27 
- Spreadsheet: https://docs.google.com/spreadsheets/d/14DGMpwCytBk99sRAJpqwVCh0sWFfl4k4slUoT44Idus/edit#gid=0
- Github Repo: https://github.com/Rise-Vision/client-content-michigan-flint (Contains files for the content in other placeholders. Probably not very relevant but included anyways.)

**Comment by alanclayton** [comment]
@rodrigopavezi Wasn't this resolved w/ https://github.com/Rise-Vision/widget-google-spreadsheet/pull/278?

If so, can you close?

**Comment by rodrigopavezi** [comment]
@alanclayton it was resolved. closing it. cheers
