### ISSUE TITLE
When scrolling By Page, the Pause Value is always 10 seconds, regardless of what is entered.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#282]
<b>How it works now:</b>
1. Add the Spreadsheet Widget to a Presentation, set it to scroll by Page, and set a pause of 20 seconds.
2. Notice that in preview and on the Display, the pause is always 10 seconds. You can modify the pause time to any option, it always goes with 10 seconds.

For further clarification: https://goo.gl/RBT4vb

<b>How it should work</b>
The Widget should adhere to the time set as the pause value.

Presentation to test with: https://apps.risevision.com/editor/workspace/692c3b25-e805-405e-94f1-49ad62a865a3/true?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 282: When scrolling By Page, the Pause Value is always 10 seconds, regardless of what is entered.](https://trello.com/c/wMIp7M0U/5069-1-issue-282-when-scrolling-by-page-the-pause-value-is-always-10-seconds-regardless-of-what-is-entered)

**Comment by stulees** [comment]
@robb-price Fixed by PR #283
