### ISSUE TITLE
Can't pick a spreadsheet through the drive picker.

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-google-spreadsheet#291]
When users go to the Spreadsheet Widget they are unable to pick a spreadsheet with the drive picker and see this error message.

![screen shot 2018-01-30 at 9 09 07 am](https://user-images.githubusercontent.com/9273546/35573608-96dc543a-05a5-11e8-9f9d-686a73cbfb0b.png)

[Community post](https://help.risevision.com/hc/en-us/community/posts/360000477403)

**Comment by rodrigopavezi** [comment]
This has been fixed by moving widget settings to gcs and verifying the client id with google.
