### ISSUE TITLE
Changing the name of the first sheet stops the widget from displaying

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/widget-google-spreadsheet#296]
In some instances changing the name of a sheet in a public spreadsheet (used by our spreadsheet widget) can cause it to get the error. I was not able to get this error every time but I did get a video of it. Even after deleting and re-adding the spreadsheet widget it still shows this error both in the editor and when trying to preview.

![image](https://user-images.githubusercontent.com/27289926/40739834-7349ff3c-6404-11e8-8d92-b929d3721b44.png)

In preview:

![image](https://user-images.githubusercontent.com/27289926/40739859-8309da14-6404-11e8-8682-5af61a3ebab5.png)

Steps to replicate are in this video:

https://goo.gl/K9XrM1

**Comment by sheadarlison** [comment]
Thanks @tylermwight I'll review with the team tomorrow and let you know what the date to have this resolved will be.

**Comment by santiagonoguez** [comment]
@tylermwight we added an explicit message on settings to let the user know that if he changes settings, he needs to explicitly select again the correct sheet on the settings page. Also, now the spreadsheet settings cannot be saved if a worksheet is not selected. And finally both settings and the widget has a more explicit error message now. Please review the changes.

@sheadarlison FYI

**Comment by santiagonoguez** [comment]
Closing this after review !
