### ISSUE TITLE
Scrolling doesn't loop infinitely like the old Gadget

### ISSUE THREAD

**Issue by slaugaus** [Rise-Vision/widget-google-spreadsheet#305]
Since the Classic Editor is being disabled, we will need parity between the Gadgets that we'll lose access to and the Widgets that we'll keep access to.
**Settings I'm using:**
- Show Entire Sheet
- No headers
- Scroll: Continuously
- Pause: 0
- PUD Failover: 0
- This widget is the only object in its Placeholder.

**Expected results:**
The widget should continuously scroll through the sheet's content, starting over from the beginning after the last row so it will never stop scrolling. This is the same behavior as the Gadget that was available in the Classic Editor.

**Actual results:**
The widget scrolls through the content once, fades out, and reloads at the beginning of the content, leaving the area it occupies blank for a second.

**Comment by sheadarlison** [comment]
Hi @slaugaus, 

We won't be adding this feature to the Spreadsheet Widget but if you'd like to take the open source code and implement it yourself you are welcome to. 

Thanks,
Shea
