### ISSUE TITLE
Widget does not show on a Licensed ChromeOS Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#308]
### What is the expected behavior?
Spreadsheet should play in Chrome the same way it does on Linux, Windows, and Pi.

### What is the actual behavior?
The Spreadsheet Widget does not show.

### What steps can be taken to replicate the problem?
Add the Spreadsheet Widget with a Published to the Web and "Anyone with the link can view" Spreadsheet, and notice that you can see it on all licensed devices except ChromeOS.

This appears on Chrome versions 68.0.3440.87 and 59.0.3071.91, but not Chrome 67.

**Comment by sheadarlison** [comment]
This is fixed. Closing the issue.
