### ISSUE TITLE
Odd and Even Colors Not Working

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/widget-google-spreadsheet#309]
**Reproduction Steps**
1. Create a presentation with a spreadsheet widget. 
2. Adjust the odd and even row color values and save.
3. Wait for the widget to refresh.

**Expected Results**

Color should change when new color values are applied.

**Actual Results**

The spreadsheet widget retains its previous color settings and does not acquire the new ones. Fonts still work though. Color value numbers are saved in the config, but not actually used in the presentation.

**Comment by sheadarlison** [comment]
Not a defect, settings we're just applied incorrectly.
