### ISSUE TITLE
Widget shows error message that it cannot load when it starts without network

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#315]
### What is the expected behavior?
The Spreadsheet Widget should load and play as expected when the network is not available.

### What is the actual behavior?
If the Display starts without a network connection, the Spreadsheet Widget will sometimes not show the spreadsheet data, and instead show only the error "There was an error accessing your spreadsheet data. Please ensure a valid range and worksheet has been selected". When the network is connected again, the spreadsheet will work as expected.

### What steps can be taken to replicate the problem?
So far I have not been able to replicate, but we have a user who is able to replicate this with a degree of reliability. The attached image is from their testing.

![Spreadsheet Widget Error](https://user-images.githubusercontent.com/6862256/75383451-5ad7d400-58aa-11ea-824c-d70a59242206.jpg)

**Comment by santiagonoguez** [comment]
it's an issue with how cache is handled by the component. Uninstalling / reinstalling works as a workaround, and if that does not help then using a new copy of the spreadsheet is another workaround.

**Comment by stulees** [comment]
A fix would require modifications to Rise Cache which we are not pursuing, closing the defect, Support will respond to customer.
