### ISSUE TITLE
Google Sheets Widget seems to cache certain functions incorrectly

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/widget-google-spreadsheet#316]
### What is the expected behavior?
Functions such as =today(), =index(), are updated on the sheet and their changes are propagated to the presentation.

### What is the actual behavior?
Despite the functions updating and enough time having passed for the updates to have propagated to the presentation (especially in cases where an API key is used for refreshes), the widget continues to display old data. 

### What steps can be taken to replicate the problem?
Create a sheet that uses functions, such as =today() or =Index(Extract!C1). Add the sheet to a presentation using the Google Sheets Widget, then do something that would cause the sheet to update, such as waiting a day or modifying a cell being pulled by =index(extract). Even if an API key is used to reduce wait time, the widget will not show the new data, either in preview or on a live display.

**Comment by stulees** [comment]
@colby-maughan How many users are affected by this and is there a workaround?

**Comment by stulees** [comment]
User has a workaround, closing the issue.
