### ISSUE TITLE
Widget Version 0.1.0 no longer shows any data from Spreadsheet

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#319]
### What is the expected behavior?
The content from the Google Spreadsheet should show regardless of the Widget version.

### What is the actual behavior?
Widget version 0.1.0 will no longer show data as it uses the now deprecated sheets api v3.

### What steps can be taken to replicate the problem?
Preview any Presentation still using Google Spreadsheet Widget 0.1.0. This does not happen with the latest version of the Spreadsheet Widget.

**Comment by stulees** [comment]
@robb-price This has been resolved with a manual fix to the production code of the 0.1.0 version of widget. You can validate with this presentation - https://apps.risevision.com/editor/workspace/c5a1f306-3c8f-41f5-880b-1b72ea8f709f?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f.
