### ISSUE TITLE
Uptime errors not published to user

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-spreadsheet#324]
The following uptime errors are being reported, but they are not being published to the User:

- E000000081
- E000000082
- E000000083
- E000000084
-

**Comment by stulees** [comment]
@alanclayton Can you clarify why this has been opened given the widget does display a message that pertains to particular API error status code? Depending on which one, we also provide an action to correct.

**Comment by alanclayton** [comment]
@stulees Per discussion at SoS, we need to notify our users via In App or email, but not on the display. Thanks

**Comment by ezequielc** [comment]
@stulees Closing as per https://github.com/Rise-Vision/rise-twitter/issues/70#issuecomment-916420515. Thanks
