### ISSUE TITLE
Spreadsheet Widget can't be configured to refresh every 1 minute.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#325]
### How to reproduce
Add a spreadsheet widget with a custom API key. Attempt to set the refresh to 1 minute.

### What happens
Error message stating that the minimum is 10 minutes.

### What should happen
User is requesting if using a custom API key they should be able to refresh every 1 minute.

**Comment by stulees** [comment]
@btfrise Please see #321 . We are addressing a problem of users exceeding their API quota and have actively been enforcing a new minimum refresh rate. We can not support 1 minute. @alanclayton FYI
