### ISSUE TITLE
If there are multiple placeholders, with multiple widgets set to the same duration, they do not rotate together.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-spreadsheet#330]
### How to recreate
Create a presentation with 3 placeholders.
Put 3 pieces of content in each placeholder.
Set the duration of each piece of content to 15 seconds.
Preview.

### What happens
The content will not rotate synchronously.

### Additional information
Reported by user with this presentation. He says they have been using this same format for around 2 years and the content has rotated as expected until 19-October-2020.

**Comment by stulees** [comment]
@btfrise  A fix to alleviate this synchronization issue has been deployed. 

Note, it does not resolve synchronization when presentation (with spreadsheet widget instances) is running for first time (no data is cached). It is at the mercy of instances requesting for data at different random times which was to alleviate issue Rise-Vision/widget-google-spreadsheet#321 . 

Once presentation (widget instances) has ran for at least 1 minute for the first time, doing a refresh/reboot will get all instances in sync. Any subsequent play/refresh/reboot will also ensure all instances are in sync.
