### ISSUE TITLE
If there are multiple instances of the Spreadsheet Widget in a Placeholder, and the transition is None, only the last one is swipeable.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#88]
<b>How it works now</b>
Use a Presentation with multiple instances of the Spreadsheet Widget in one Placeholder, and the Placeholder transition is None. Notice that the first Spreadsheets are not swipeable, but the last Spreadsheet is. This was originally logged as <a href="https://code.google.com/p/risegadgets/issues/detail?id=1128">Issue 1128</a>. Previously it only occurred when the Spreadsheet was set to scroll By Page, but now it occurs with both. Also, in the original issue it was the first Spreadsheet that was swipeable, not the last.

This issue occurs on Windows PAP and Chrome but does not occur on Linux PAP, Mac PAP, Windows Native, and Linux Native.

@stulees Let me know a Company I can put the Presentation into that shows these issues.

**Comment by alanclayton** [comment]
Unable to replicate. Likely resolved with a Chrome update. Closing issue. @stulees FYI
