### ISSUE TITLE
When video and the Spreadsheet Widget are in the same Placeholder, the Spreadsheet is not swipeable on Windows PAP and Chrome

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#94]
<b>How it works now</b>
When video and the Spreadsheet Widget are in the same Placeholder, the Spreadsheet is not swipeable on Chrome or Windows PAP. On other OS'/Players, it swipes successfully.

<b>How it should work</b>
The Spreadsheet should swipe on all OS' in the same way regardless of what else is in the Placeholder.

**Comment by alanclayton** [comment]
Can't replicate this issue. Closing. @stulees @robb-price @mmeiers FYI
