### ISSUE TITLE
If there are multiple Presentations each with Spreadsheet Widget in them, only the last one is swipeable on Chrome and Windows PAP

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-spreadsheet#95]
<b>How it works now:</b>
Have a Schedule with 2 Presentations, each Presentation has scrolling Spreadsheet Widgets. Notice that on Windows PAP and Chrome, they are not swipeable. This does not happen on other OS'/Players.

This issue is similar to <a href="https://github.com/Rise-Vision/widget-google-spreadsheet/issues/88">Issue 88</a>.

<b>How it should work:</b>
The Spreadsheets should be swipeable in all Presentations in a Schedule.

**Comment by alanclayton** [comment]
I can not replicate this. Likely fixed with a Chrome update. Closing issue. @mmeiers @dlugo00 @robb-price @stulees  FYI.
